version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: go_pg
    restart: always
    environment:
      POSTGRES_USER: new_user
      POSTGRES_PASSWORD: new_pass123
      POSTGRES_DB: new_db
    ports:
      - "15432:5432"   # хост:контейнер
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.15.2
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://new_user:new_pass123@postgres:5432/new_db?sslmode=disable",
      "up"
    ]
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
